// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmqzpzogltoeqnbehioa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcXpwem9nbHRvZXFuYmVoaW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjMwNzcsImV4cCI6MjA2OTk5OTA3N30.FaBap8MZ0L_JXCFKeZDOH0m9ql1LwyyjcPy7exwWoic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});